builders:
  embed:
    import: "package:embed/embed.dart"
    builder_factories: ["embedBuilder"]
    build_extensions: { ".dart": ["embed.g.part"] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
