name: embed
description: A code generator for embedding external content into your Dart code.
version: 0.0.0
repository: https://github.com/fujidaiti/embed.dart.git

environment:
  sdk: ">=3.0.5 <4.0.0"

dev_dependencies:
  lints: ^2.1.1
