[tasks.validate-example]
cwd = './example'
script = '''
dart pub get
dart run build_runner clean
dart run build_runner build --delete-conflicting-outputs
dart analyze
'''

[tasks.validate-annotation]
cwd = './embed_annotation'
script = '''
dart pub get
pana --exit-code-threshold 10
'''

[tasks.validate-embed]
cwd = './embed'
script = '''
dart pub get
dart run build_runner clean
dart run build_runner build --delete-conflicting-outputs
dart test
pana --exit-code-threshold 10
'''

[tasks.validate]
run_task = { name = [
  "validate-example",
  "validate-annotation",
  "validate-embed",
] }
