name: PR Validation
run-name: Validation for ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches: [master]
jobs:
  validation:
    name: PR validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Install pana
        run: dart pub global activate pana

      - name: Install cargo-make
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --debug cargo-make

      - name: Validate packages
        uses: actions-rs/cargo@v1
        with:
          command: make
          args: validate
