name: PR Validation
run-name: Validation for ${{ github.event.pull_request.title }}
on:
  pull_request:
    branches: [master]
jobs:
  validation:
    name: PR validation
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [./embed, ./embed_annotation]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Dart SDK
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: Dart versioin
        run: dart --version

      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: dart pub get

      - name: Run build_runner
        working-directory: ${{ matrix.package }}
        run: dart run build_runner clean && dart run build_runner build

      - name: Analize
        working-directory: ${{ matrix.package }}
        run: dart analyze

      - name: Tests
        working-directory: ${{ matrix.package }}
        run: dart test

      - name: Dry publish
        working-directory: ${{ matrix.package }}
        run: dart pub publish --dry-run
